### ISSUE TITLE
USER STORY: Checklist for travelling or the next adventure.

### ISSUE THREAD

**Issue by PdoyleC** [PdoyleC/live-life#37]
As a user, **I can add a list of items** so that **I know what I need for my next adventure**.

**Acceptance Criteria:**

- [x] User can add items to a list.
- [x] User can deleted items from the list.
- [x] User can edit items from the list.
- [x] Qty needed.
- [x] Yes/No if it needs to be got.

**Comment by PdoyleC** [comment]
user has full CRUD with the list
